CREATE DATABASE TCC;
USE TCC;

CREATE TABLE IF NOT EXISTS Curso(
idCurso INT NOT NULL AUTO_INCREMENT,
Curso VARCHAR (45) NOT NULL,
CONSTRAINT PK_CURSO PRIMARY KEY (idCURSO)
);

CREATE TABLE IF NOT EXISTS LinhaPesquisa(
idLinhaPesquisa INT NOT NULL AUTO_INCREMENT,
LinhaPesquisa VARCHAR (250) NOT NULL,
idCursoFK INT,
CONSTRAINT PK_LinhaPesquisa PRIMARY KEY (idLinhaPesquisa),
CONSTRAINT FKCurso FOREIGN KEY (idCursoFK) REFERENCES Curso (idCurso)
);

CREATE TABLE IF NOT EXISTS Professor(
idProfessor INT NOT NULL AUTO_INCREMENT,
NomeProfessor VARCHAR (100) NOT NULL,
MatriculaProfessor CHAR (9) NOT NULL,
EmailProfessor VARCHAR (50) NOT NULL,
LoginProfessor VARCHAR (50) NOT NULL,
SenhaProfessor VARCHAR (20) NOT NULL,
CONSTRAINT ProfessorPK PRIMARY KEY (idProfessor)
);
 
CREATE TABLE IF NOT EXISTS Aluno(
idAluno INT NOT NULL AUTO_INCREMENT,
NomeAluno VARCHAR (100) NOT NULL,
MatriculaAluno CHAR (9) NOT NULL,
EmailAluno VARCHAR (50) NOT NULL,
LoginAluno VARCHAR (50) NOT NULL,
SenhaAluno VARCHAR (20) NOT NULL,
idCursoFK INT,
CONSTRAINT AlunoPK PRIMARY KEY (idAluno),
CONSTRAINT FKCurso2 FOREIGN KEY (idCursoFK) REFERENCES Curso (idCurso)
);

CREATE TABLE IF NOT EXISTS Eventos(
idEventos INT NOT NULL AUTO_INCREMENT,
NomeEventos VARCHAR (100) NOT NULL,
DataEvento DATETIME NOT NULL,
LocalEventos VARCHAR (100) NOT NULL,
idProfessorFK INT,
idCursoFK INT,
CONSTRAINT EventosPK PRIMARY KEY (idEventos),
CONSTRAINT FKProfessor FOREIGN KEY (idProfessorFK) REFERENCES Professor (idProfessor),
CONSTRAINT FKCurso3 FOREIGN KEY (idCursoFK) REFERENCES Curso (idCurso)
);

CREATE TABLE IF NOT EXISTS Agendamento(
idAgendamento INT NOT NULL AUTO_INCREMENT,
Motivo VARCHAR (100) NOT NULL,
DataHora DATETIME NOT NULL,
idProfessorFK INT,
idAlunoFK INT,
CONSTRAINT AgendamentoPK PRIMARY KEY (idAgendamento),
CONSTRAINT FKProfessor2 FOREIGN KEY (idProfessorFK) REFERENCES Professor (idProfessor),
CONSTRAINT FKAluno FOREIGN KEY (idAlunoFK) REFERENCES Aluno (idAluno)
);

CREATE TABLE IF NOT EXISTS TCC(
idTCC INT NOT NULL AUTO_INCREMENT,
Titutlo VARCHAR (100) NOT NULL,
Descricao VARCHAR (250) NOT NULL,
Status BOOLEAN,
Objetivo VARCHAR (100) NOT NULL,
Justificativa VARCHAR (100),
TCCTipo BOOLEAN NOT NULL,
idLinhaPesquisaFK INT,
CONSTRAINT TCCPK PRIMARY KEY (idTCC),
CONSTRAINT FKLinhaPesquisa FOREIGN KEY (idLinhaPesquisaFK) REFERENCES LinhaPesquisa (idLinhaPesquisa)
);

CREATE TABLE IF NOT EXISTS Componentes(
idComponentes INT NOT NULL AUTO_INCREMENT,
idProfessorFK INT,
idAlunoFK1 INT,
idAlunoFK2 INT,
idTCCFK INT,
CONSTRAINT ComponentesPK PRIMARY KEY (idComponentes),
CONSTRAINT FKProfessor3 FOREIGN KEY (idProfessorFK) REFERENCES Professor (idProfessor),
CONSTRAINT FKAluno1 FOREIGN KEY (idAlunoFK1) REFERENCES Aluno (idAluno),
CONSTRAINT FKAluno2 FOREIGN KEY (idAlunoFK2) REFERENCES Aluno (idAluno),
CONSTRAINT FKTCC FOREIGN KEY (idTCCFK) REFERENCES TCC (idTCC)
);

CREATE TABLE IF NOT EXISTS Relatorio(
idRelatorio INT NOT NULL AUTO_INCREMENT,
Apresetacao VARCHAR (250) NOT NULL,
Fundamentacao VARCHAR (250) NOT NULL,
Desenvolvimento VARCHAR (250) NOT NULL,
ModeloResultado VARCHAR (250) NOT NULL,
NotaTotal CHAR (4),
TipoRelatorio VARCHAR (50) NOT NULL,
ApresentacaoComentario VARCHAR (250) NOT NULL,
FundamentacaoComentario VARCHAR (250) NOT NULL,
DesenvolvimentoComentario VARCHAR (250) NOT NULL,
ModeloResultadoComentario VARCHAR (250) NOT NULL,
idTCCFK INT,
CONSTRAINT RelatorioPK PRIMARY KEY (idRelatorio),
CONSTRAINT FKTCC2 FOREIGN KEY (idTCCFK) REFERENCES TCC (idTCC)
);

CREATE TABLE IF NOT EXISTS Atividades(
idAtividades INT NOT NULL AUTO_INCREMENT,
NomeAtividades VARCHAR (50) NOT NULL,
MesAtividade DATE NOT NULL,
DescricaoAtividade VARCHAR (250) NOT NULL,
idTCCFK INT,
CONSTRAINT AtividadePK PRIMARY KEY (idAtividades),
CONSTRAINT FKTCC3 FOREIGN KEY (idTCCFK) REFERENCES TCC (idTCC)
);
 
CREATE TABLE IF NOT EXISTS Arquivos(
idArquivos INT NOT NULL AUTO_INCREMENT,
Link VARCHAR (250) NOT NULL,
StatusArquivo BOOLEAN,
idTCCFK INT,
CONSTRAINT AequivosPK PRIMARY KEY (idArquivos),
CONSTRAINT FKTCC4 FOREIGN KEY (idTCCFK) REFERENCES TCC (idTCC)
);

CREATE TABLE IF NOT EXISTS Erros(
idErros INT NOT NULL AUTO_INCREMENT,
Nome VARCHAR (50) NOT NULL,
Categoria VARCHAR (100) NOT NULL,
CONSTRAINT ErrosPK PRIMARY KEY (idErros)
);

CREATE TABLE IF NOT EXISTS ErrosTCC(
idErrosTCC INT NOT NULL AUTO_INCREMENT,
idTCCFK INT,
idErrosFK INT,
CONSTRAINT ErrosTCC PRIMARY KEY (idErrosTCC),
CONSTRAINT FKTCC6 FOREIGN KEY (idTCCFK) REFERENCES TCC (idTCC),
CONSTRAINT FKErros1 FOREIGN KEY (idERROS) REFERENCES Erros (idERROS)
);

CREATE TABLE IF NOT EXISTS SalaAula(
idSalaAula INT NOT NULL AUTO_INCREMENT,
Setor VARCHAR (50) NOT NULL,
Capacidade VARCHAR (20) NOT NULL,
Unidade VARCHAR (50) NOT NULL,
CONSTRAINT SalaAulaPK PRIMARY KEY (idSalaAula)
);

CREATE TABLE IF NOT EXISTS Reserva(
idReserva INT NOT NULL AUTO_INCREMENT,
DataHora DATETIME NOT NULL,
idProfessorFK INT,
idSalaAulaFK INT,
CONSTRAINT ReservaPK PRIMARY KEY (idReserva),
CONSTRAINT FKProfessor4 FOREIGN KEY (idProfessorFK) REFERENCES Professor (idProfessor),
CONSTRAINT FKSalaAula FOREIGN KEY (idSalaAulaFK) REFERENCES SalaAula (idSalaAula)
);

CREATE TABLE IF NOT EXISTS Defesa(
idDefesa INT NOT NULL AUTO_INCREMENT,
PosturaPessoal VARCHAR (250) NOT NULL,
FluenciaComunicativa VARCHAR (250) NOT NULL,
Clareza VARCHAR (250) NOT NULL,
Dominio VARCHAR (250) NOT NULL,
NotaFinal CHAR (4) NOT NULL,
PosturaComentario VARCHAR (250) NOT NULL,
FluenciaComentario VARCHAR (250) NOT NULL,
ClarezaComentario VARCHAR (250) NOT NULL,
DominioComentario VARCHAR (250) NOT NULL,
DataBanca DATE NOT NULL,
idTCCFK INT,
idReservaFK INT,
CONSTRAINT DefesaPK PRIMARY KEY (idDefesa),
CONSTRAINT FKTCC5 FOREIGN KEY (idTCCFK) REFERENCES TCC (idTCC),
CONSTRAINT FKReserva FOREIGN KEY (idReservaFK) REFERENCES Reserva (idReserva)
);

CREATE TABLE IF NOT EXISTS Cronograma(
idCronograma INT NOT NULL AUTO_INCREMENT,
PorQue VARCHAR (100),
Onde VARCHAR (100),
Quando VARCHAR (100),
Quem VARCHAR (100),
Como VARCHAR (100),
Quanto VARCHAR (100),
CONSTRAINT CronogramaPK PRIMARY KEY (idCronograma)
);

CREATE TABLE IF NOT EXISTS AtividadesCronograma(
idAtividadesCronograma INT NOT NULL AUTO_INCREMENT,
NomeAtividades VARCHAR (100),
idCronogramaFK INT,
idTCCFK INT,
CONSTRAINT AtividadesCronogramaPK PRIMARY KEY (idAtividadesCronograma),
CONSTRAINT FKCronograma FOREIGN KEY (idCronogramaFK) REFERENCES Cronograma (idCronograma),
CONSTRAINT FKTCC7 FOREIGN KEY (idTCCFK) REFERENCES TCC (idTCC)
);