-- MySQL Script generated by MySQL Workbench
-- Sat Nov  5 15:22:57 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema estartho_bdunp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `estartho_bdunp` ;

-- -----------------------------------------------------
-- Schema estartho_bdunp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estartho_bdunp` DEFAULT CHARACTER SET latin1 ;


-- -----------------------------------------------------
-- Table `Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Curso` ;

CREATE TABLE IF NOT EXISTS `Curso` (
  `idCurso` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeCurso` VARCHAR(45) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE UNIQUE INDEX `nomeCurso_UNIQUE` ON `Curso` (`nomeCurso` ASC);

CREATE UNIQUE INDEX `idCurso_UNIQUE` ON `Curso` (`idCurso` ASC);


-- -----------------------------------------------------
-- Table `Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluno` ;

CREATE TABLE IF NOT EXISTS `Aluno` (
  `idAluno` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `matricula` CHAR(9) CHARACTER SET 'latin1' NOT NULL,
  `email` VARCHAR(50) CHARACTER SET 'latin1' NOT NULL,
  `login` VARCHAR(50) CHARACTER SET 'latin1' NOT NULL,
  `senha` VARCHAR(20) CHARACTER SET 'latin1' NOT NULL,
  `idCursoFK` INT(11) NOT NULL,
  PRIMARY KEY (`idAluno`),
  CONSTRAINT `FKCurso_Aluno`
    FOREIGN KEY (`idCursoFK`)
    REFERENCES `Curso` (`idCurso`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE INDEX `FKCurso_Aluno` ON `Aluno` (`idCursoFK` ASC);

CREATE UNIQUE INDEX `idAluno_UNIQUE` ON `Aluno` (`idAluno` ASC);

CREATE UNIQUE INDEX `matricula_UNIQUE` ON `Aluno` (`matricula` ASC);

CREATE UNIQUE INDEX `email_UNIQUE` ON `Aluno` (`email` ASC);

CREATE UNIQUE INDEX `login_UNIQUE` ON `Aluno` (`login` ASC);


-- -----------------------------------------------------
-- Table `Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Professor` ;

CREATE TABLE IF NOT EXISTS `Professor` (
  `idProfessor` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `matricula` VARCHAR(6) CHARACTER SET 'latin1' NOT NULL,
  `email` VARCHAR(50) CHARACTER SET 'latin1' NOT NULL,
  `login` VARCHAR(50) CHARACTER SET 'latin1' NOT NULL,
  `senha` VARCHAR(20) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`idProfessor`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE UNIQUE INDEX `idProfessor_UNIQUE` ON `Professor` (`idProfessor` ASC);

CREATE UNIQUE INDEX `matricula_UNIQUE` ON `Professor` (`matricula` ASC);

CREATE UNIQUE INDEX `login_UNIQUE` ON `Professor` (`login` ASC);

CREATE UNIQUE INDEX `email_UNIQUE` ON `Professor` (`email` ASC);


-- -----------------------------------------------------
-- Table `Agendamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agendamento` ;

CREATE TABLE IF NOT EXISTS `Agendamento` (
  `idAgendamento` INT(11) NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `dataHora` DATETIME NOT NULL,
  `idProfessorFK` INT(11) NULL DEFAULT NULL,
  `idAlunoFK` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idAgendamento`),
  CONSTRAINT `FKAluno_Agendamento`
    FOREIGN KEY (`idAlunoFK`)
    REFERENCES `Aluno` (`idAluno`),
  CONSTRAINT `FKProfessor_Agendamento`
    FOREIGN KEY (`idProfessorFK`)
    REFERENCES `Professor` (`idProfessor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE INDEX `FKProfessor_Agendamento` ON `Agendamento` (`idProfessorFK` ASC);

CREATE INDEX `FKAluno_Agendamento` ON `Agendamento` (`idAlunoFK` ASC);

CREATE UNIQUE INDEX `idAgendamento_UNIQUE` ON `Agendamento` (`idAgendamento` ASC);


-- -----------------------------------------------------
-- Table `LinhaPesquisa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LinhaPesquisa` ;

CREATE TABLE IF NOT EXISTS `LinhaPesquisa` (
  `idLinhaPesquisa` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) CHARACTER SET 'latin1' NOT NULL,
  `idCursoFK` INT(11) NOT NULL,
  PRIMARY KEY (`idLinhaPesquisa`),
  CONSTRAINT `FKCurso_LinhaPesquisa`
    FOREIGN KEY (`idCursoFK`)
    REFERENCES `Curso` (`idCurso`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE INDEX `FKCurso_LinhaPesquisa` ON `LinhaPesquisa` (`idCursoFK` ASC);

CREATE UNIQUE INDEX `idLinhaPesquisa_UNIQUE` ON `LinhaPesquisa` (`idLinhaPesquisa` ASC);

CREATE UNIQUE INDEX `LinhaPesquisa_UNIQUE` ON `LinhaPesquisa` (`nome` ASC);


-- -----------------------------------------------------
-- Table `TCC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TCC` ;

CREATE TABLE IF NOT EXISTS `TCC` (
  `idTCC` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `resumo` VARCHAR(250) CHARACTER SET 'latin1' NOT NULL,
  `statusTCC` TINYINT(1) NOT NULL COMMENT '1 - Finalizado\n2 - Pendente\n3 - Negado\n4 - Aceite',
  `objetivo` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `justificativa` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `TCCTipo` TINYINT(1) NOT NULL,
  `idLinhaPesquisaFK` INT(11) NOT NULL,
  PRIMARY KEY (`idTCC`),
  CONSTRAINT `FKLinhaPesquisa_TCC`
    FOREIGN KEY (`idLinhaPesquisaFK`)
    REFERENCES `LinhaPesquisa` (`idLinhaPesquisa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE INDEX `FKLinhaPesquisa_TCC` ON `TCC` (`idLinhaPesquisaFK` ASC);

CREATE UNIQUE INDEX `idTCC_UNIQUE` ON `TCC` (`idTCC` ASC);

CREATE UNIQUE INDEX `titulo_UNIQUE` ON `TCC` (`titulo` ASC);


-- -----------------------------------------------------
-- Table `Arquivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Arquivo` ;

CREATE TABLE IF NOT EXISTS `Arquivo` (
  `idArquivo` INT(11) NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(250) CHARACTER SET 'latin1' NOT NULL,
  `idTCCFK` INT(11) NOT NULL,
  `versao` VARCHAR(45) NOT NULL COMMENT 'TCC 1\nTCC 2\nBanca\nFinal com correções\n',
  PRIMARY KEY (`idArquivo`),
  CONSTRAINT `FKTCC_Arquivo`
    FOREIGN KEY (`idTCCFK`)
    REFERENCES `TCC` (`idTCC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE INDEX `FKTCC_Arquivo` ON `Arquivo` (`idTCCFK` ASC);

CREATE UNIQUE INDEX `idArquivo_UNIQUE` ON `Arquivo` (`idArquivo` ASC);


-- -----------------------------------------------------
-- Table `Atividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Atividade` ;

CREATE TABLE IF NOT EXISTS `Atividade` (
  `idAtividade` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) CHARACTER SET 'latin1' NOT NULL,
  `mes` DATE NOT NULL,
  `descricao` VARCHAR(250) CHARACTER SET 'latin1' NOT NULL,
  `idTCCFK` INT(11) NOT NULL,
  PRIMARY KEY (`idAtividade`),
  CONSTRAINT `FKTCC_Atividade`
    FOREIGN KEY (`idTCCFK`)
    REFERENCES `TCC` (`idTCC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE INDEX `FKTCC_Atividade` ON `Atividade` (`idTCCFK` ASC);

CREATE UNIQUE INDEX `idAtividade_UNIQUE` ON `Atividade` (`idAtividade` ASC);


-- -----------------------------------------------------
-- Table `Cronograma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cronograma` ;

CREATE TABLE IF NOT EXISTS `Cronograma` (
  `idCronograma` INT(11) NOT NULL AUTO_INCREMENT,
  `oque` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `porque` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `onde` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `quando` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `quem` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `como` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `quanto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCronograma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE UNIQUE INDEX `idCronograma_UNIQUE` ON `Cronograma` (`idCronograma` ASC);


-- -----------------------------------------------------
-- Table `AtividadesCronograma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AtividadesCronograma` ;

CREATE TABLE IF NOT EXISTS `AtividadesCronograma` (
  `idAtividadesCronograma` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `idCronogramaFK` INT(11) NOT NULL,
  `idTCCFK` INT(11) NOT NULL,
  PRIMARY KEY (`idAtividadesCronograma`),
  CONSTRAINT `FKCronograma_AtividadesCronograma`
    FOREIGN KEY (`idCronogramaFK`)
    REFERENCES `Cronograma` (`idCronograma`),
  CONSTRAINT `FKTCC_AtividadesCronograma`
    FOREIGN KEY (`idTCCFK`)
    REFERENCES `TCC` (`idTCC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE INDEX `FKCronograma_AtividadesCronograma` ON `AtividadesCronograma` (`idCronogramaFK` ASC);

CREATE INDEX `FKTCC_AtividadesCronograma` ON `AtividadesCronograma` (`idTCCFK` ASC);

CREATE UNIQUE INDEX `idAtividadesCronograma_UNIQUE` ON `AtividadesCronograma` (`idAtividadesCronograma` ASC);


-- -----------------------------------------------------
-- Table `Componentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Componentes` ;

CREATE TABLE IF NOT EXISTS `Componentes` (
  `idProfessorFK` INT(11) NOT NULL,
  `idAlunoFK1` INT(11) NOT NULL,
  `idAlunoFK2` INT(11) NULL DEFAULT NULL,
  `idTCCFK` INT(11) NOT NULL,
  CONSTRAINT `FKAluno_Componente`
    FOREIGN KEY (`idAlunoFK1`)
    REFERENCES `Aluno` (`idAluno`),
  CONSTRAINT `FKAluno_Componente_2`
    FOREIGN KEY (`idAlunoFK2`)
    REFERENCES `Aluno` (`idAluno`),
  CONSTRAINT `FKProfessor_Componente`
    FOREIGN KEY (`idProfessorFK`)
    REFERENCES `Professor` (`idProfessor`),
  CONSTRAINT `FKTCC_Componente`
    FOREIGN KEY (`idTCCFK`)
    REFERENCES `TCC` (`idTCC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE INDEX `FKProfessor_Componente` ON `Componentes` (`idProfessorFK` ASC);

CREATE INDEX `FKAluno_Componente` ON `Componentes` (`idAlunoFK1` ASC);

CREATE INDEX `FKAluno_Componente_2` ON `Componentes` (`idAlunoFK2` ASC);

CREATE INDEX `FKTCC_Componente` ON `Componentes` (`idTCCFK` ASC);


-- -----------------------------------------------------
-- Table `Unidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Unidade` ;

CREATE TABLE IF NOT EXISTS `Unidade` (
  `idUnidade` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUnidade`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idUnidade_UNIQUE` ON `Unidade` (`idUnidade` ASC);


-- -----------------------------------------------------
-- Table `Sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sala` ;

CREATE TABLE IF NOT EXISTS `Sala` (
  `idSala` INT(11) NOT NULL AUTO_INCREMENT,
  `setor` VARCHAR(10) CHARACTER SET 'latin1' NOT NULL,
  `nome` VARCHAR (20) NOT NULL,
  `capacidade` INT NOT NULL,
  `idUnidadeFK` INT NOT NULL,
  PRIMARY KEY (`idSala`),
  CONSTRAINT `fk_Sala_Unidade`
    FOREIGN KEY (`idUnidadeFK`)
    REFERENCES `Unidade` (`idUnidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE INDEX `fk_Sala_Unidade1_idx` ON `Sala` (`idUnidadeFK` ASC);

CREATE UNIQUE INDEX `idSala_UNIQUE` ON `Sala` (`idSala` ASC);


-- -----------------------------------------------------
-- Table `Reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reserva` ;

CREATE TABLE IF NOT EXISTS `Reserva` (
  `idReserva` INT(11) NOT NULL AUTO_INCREMENT,
  `dataHora` DATETIME NOT NULL,
  `idProfessorFK` INT(11) NOT NULL,
  `idSalaFK` INT(11) NOT NULL,
  PRIMARY KEY (`idReserva`),
  CONSTRAINT `FKProfessor_Reserva`
    FOREIGN KEY (`idProfessorFK`)
    REFERENCES `Professor` (`idProfessor`),
  CONSTRAINT `FKSalaAula_Reserva`
    FOREIGN KEY (`idSalaFK`)
    REFERENCES `Sala` (`idSala`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE INDEX `FKProfessor_Reserva` ON `Reserva` (`idProfessorFK` ASC);

CREATE INDEX `FKSalaAula_Reserva` ON `Reserva` (`idSalaFK` ASC);

CREATE UNIQUE INDEX `idReserva_UNIQUE` ON `Reserva` (`idReserva` ASC);


-- -----------------------------------------------------
-- Table `Defesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Defesa` ;

CREATE TABLE IF NOT EXISTS `Defesa` (
  `idDefesa` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `idTCCFK` INT(11) NOT NULL,
  `idReservaFK` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idDefesa`),
  CONSTRAINT `FKReserva_Defesa`
    FOREIGN KEY (`idReservaFK`)
    REFERENCES `Reserva` (`idReserva`),
  CONSTRAINT `FKTCC_Defesa`
    FOREIGN KEY (`idTCCFK`)
    REFERENCES `TCC` (`idTCC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE INDEX `FKTCC_Defesa` ON `Defesa` (`idTCCFK` ASC);

CREATE INDEX `FKReserva_Defesa` ON `Defesa` (`idReservaFK` ASC);

CREATE UNIQUE INDEX `idDefesa_UNIQUE` ON `Defesa` (`idDefesa` ASC);


-- -----------------------------------------------------
-- Table `Erros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Erros` ;

CREATE TABLE IF NOT EXISTS `Erros` (
  `idErros` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeErro` VARCHAR(50) CHARACTER SET 'latin1' NOT NULL,
  `categoria` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`idErros`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE UNIQUE INDEX `idErros_UNIQUE` ON `Erros` (`idErros` ASC);


-- -----------------------------------------------------
-- Table `ErrosTCC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ErrosTCC` ;

CREATE TABLE IF NOT EXISTS `ErrosTCC` (
  `idErrosTCC` INT(11) NOT NULL AUTO_INCREMENT,
  `idTCCFK` INT(11) NOT NULL,
  `idErrosFK` INT(11) NOT NULL,
  PRIMARY KEY (`idErrosTCC`),
  CONSTRAINT `FKErros_ErrosTCC`
    FOREIGN KEY (`idErrosFK`)
    REFERENCES `Erros` (`idErros`),
  CONSTRAINT `FKTCC_ErrosTCC`
    FOREIGN KEY (`idTCCFK`)
    REFERENCES `TCC` (`idTCC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE INDEX `FKTCC_ErrosTCC` ON `ErrosTCC` (`idTCCFK` ASC);

CREATE INDEX `FKErros_ErrosTCC` ON `ErrosTCC` (`idErrosFK` ASC);

CREATE UNIQUE INDEX `idErrosTCC_UNIQUE` ON `ErrosTCC` (`idErrosTCC` ASC);


-- -----------------------------------------------------
-- Table `Evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Evento` ;

CREATE TABLE IF NOT EXISTS `Evento` (
  `idEvento` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) CHARACTER SET 'latin1' NOT NULL,
  `dataHora` DATETIME NOT NULL,
  `local` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `idProfessorFK` INT(11) NOT NULL,
  `idCursoFK` INT(11) NOT NULL,
  PRIMARY KEY (`idEvento`),
  CONSTRAINT `FKCurso_Evento`
    FOREIGN KEY (`idCursoFK`)
    REFERENCES `Curso` (`idCurso`),
  CONSTRAINT `FKProfessor_Evento`
    FOREIGN KEY (`idProfessorFK`)
    REFERENCES `Professor` (`idProfessor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE INDEX `FKProfessor_Evento` ON `Evento` (`idProfessorFK` ASC);

CREATE INDEX `FKCurso_Evento` ON `Evento` (`idCursoFK` ASC);

CREATE UNIQUE INDEX `idEvento_UNIQUE` ON `Evento` (`idEvento` ASC);

CREATE UNIQUE INDEX `nome_UNIQUE` ON `Evento` (`nome` ASC);


-- -----------------------------------------------------
-- Table `Relatorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Relatorio` ;

CREATE TABLE IF NOT EXISTS `Relatorio` (
  `idRelatorio` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL, 
  `apresentacaoNota` FLOAT NOT NULL,
  `fundamentacaoNota` FLOAT NOT NULL,
  `desenvolvimentoNota` FLOAT NOT NULL,
  `resultadosNota` FLOAT NOT NULL,
  `notaFinal` FLOAT NOT NULL,
  `TipoRelatorio` VARCHAR(50) CHARACTER SET 'latin1' NOT NULL,
  `apresentacaoComentario` VARCHAR(250) CHARACTER SET 'latin1' NULL,
  `fundamentacaoComentario` VARCHAR(250) CHARACTER SET 'latin1' NULL,
  `desenvolvimentoComentario` VARCHAR(250) CHARACTER SET 'latin1' NULL,
  `resultadosComentario` VARCHAR(250) CHARACTER SET 'latin1' NULL,
  `idTCCFK` INT(11) NOT NULL,
  PRIMARY KEY (`idRelatorio`),
  CONSTRAINT `FKTCC_Relatorio`
    FOREIGN KEY (`idTCCFK`)
    REFERENCES `TCC` (`idTCC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

CREATE INDEX `FKTCC_Relatorio` ON `Relatorio` (`idTCCFK` ASC);

CREATE UNIQUE INDEX `idRelatorio_UNIQUE` ON `Relatorio` (`idRelatorio` ASC);


-- -----------------------------------------------------
-- Table `AlunoDefesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlunoDefesa` ;

CREATE TABLE IF NOT EXISTS `AlunoDefesa` (
  `notaPostura` FLOAT NOT NULL,
  `notaComunicacao` FLOAT NOT NULL,
  `notaClareza` FLOAT NOT NULL,
  `notaDominio` FLOAT NOT NULL,
  `idAluno` INT(11) NOT NULL,
  `notaFinal` FLOAT NOT NULL,
  `posturaComentario` VARCHAR(200) NULL,
  `comunicacaoComentario` VARCHAR(45) NULL,
  `clarezaComentario` VARCHAR(45) NULL,
  `dominioComentario` VARCHAR(45) NULL,
  `idDefesa` INT(11) NOT NULL,
  CONSTRAINT `fk_AlunoDefesa_Aluno`
    FOREIGN KEY (`idAluno`)
    REFERENCES `Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AlunoDefesa_Defesa`
    FOREIGN KEY (`idDefesa`)
    REFERENCES `Defesa` (`idDefesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_AlunoDefesa_Aluno1_idx` ON `AlunoDefesa` (`idAluno` ASC);

CREATE INDEX `fk_AlunoDefesa_Defesa1_idx` ON `AlunoDefesa` (`idDefesa` ASC);





-- -----------------------------------------------------
-- ------------------PROCEDURES-------------------------
-- -----------------------------------------------------

-- -----------------------------------------------------
-- procedure sp_inserirAluno
-- -----------------------------------------------------


DROP procedure IF EXISTS `sp_inserirAluno`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirAluno`(nome varchar(100), matricula char(9), email varchar(50), login varchar(50), senha varchar(20), idCursoFK integer(11))
BEGIN
	INSERT INTO `Aluno`
(`nome`,
`matricula`,
`email`,
`login`,
`senha`,
`idCursoFK`)
VALUES
(nome, matricula, email, login, senha, idCursoFK);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_alterarAluno
-- -----------------------------------------------------


DROP procedure IF EXISTS `sp_alterarAluno`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarAluno`(idAluno integer(11) ,nome varchar(100), matricula char(9), email varchar(50), login varchar(50), senha varchar(20), idCursoFK integer(11))
BEGIN
  UPDATE `Aluno`
SET
`nome` =nome,
`matricula` = matricula,
`email` = email,
`login` = login,
`senha` = senha,
`idCursoFK` = idCursoFK
WHERE `Aluno`.`idAluno` = idAluno;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_deletarAluno
-- -----------------------------------------------------


DROP procedure IF EXISTS `sp_deletarAluno`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarAluno`(idAluno integer(11))
BEGIN
DELETE FROM 
WHERE `Aluno`.`idAluno` = idAluno;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_listarAluno
-- -----------------------------------------------------


DROP procedure IF EXISTS `sp_listarAluno`;

DELIMITER $$

CREATE PROCEDURE `sp_listarAluno`()
BEGIN
SELECT * FROMAluno;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_buscarAlunoID
-- -----------------------------------------------------


DROP procedure IF EXISTS `sp_buscarAlunoID`;

DELIMITER $$

CREATE PROCEDURE `sp_buscarAlunoID`(idAluno integer(11))
BEGIN
SELECT * FROMAluno as A where A.idAluno = idAluno;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_buscarAlunoMatricula
-- -----------------------------------------------------


DROP procedure IF EXISTS `sp_buscarAlunoMatricula`;

DELIMITER $$

CREATE PROCEDURE `sp_buscarAlunoMatricula`(matricula char(9))
BEGIN
SELECT * FROMAluno where matricula = matricula;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirProfessor
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirProfessor`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirProfessor`(nome varchar(100), matricula char(6), email varchar(50), login varchar(50), senha varchar(20),)
BEGIN
  INSERT INTO `Professor`
(`nome`,
`matricula`,
`email`,
`login`,
`senha`
)
VALUES
(nome, matricula, email, login, senha);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarprofessor
-- ------------------------------------------------------


DROP procedure IF EXISTS `sp_alterarProfessor`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarProfessor` (idProfessor integer(11), nome varchar(100), matricula integer(6), email varchar(50), login varchar(50), senha varchar(20))
BEGIN
  UPDATE `Professor`
    SET 
`nome`= nome,
`matricula`= matricula,
`email`= email,
`login`=login,
`senha`= senha 
WHERE `Professor`.`idProfessor`=idProfessor;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarProfessor
-- ------------------------------------------------------


DROP procedure IF EXISTS `sp_deletarProfessor`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarProfessor`(idProfessor integer(11))
BEGIN
DELETE FROM `Professor`
WHERE `Professor`.`idProfessor` = idProfessor;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarprofessor
-- ------------------------------------------------------


DROP procedure IF EXISTS `sp_listarProfessor`;

DELIMITER $$


CREATE PROCEDURE `sp_listarProfessor`()
BEGIN
SELECT * FROM`Professor`;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirCurso
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirCurso`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirCurso`(nomeCurso varchar(45))
BEGIN
  INSERT INTO `Curso`
(`nomeCurso`)
VALUES
(nomeCurso);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_aletrarCurso
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarCurso`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarCurso` (idCurso varchar(11), nomeCurso varchar(45))
BEGIN
  UPDATE `Curso`
    SET 
`nomeCurso`= nomeCurso 
WHERE `Curso`.`idCurso`=idCurso;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarCurso
-- ------------------------------------------------------


DROP procedure IF EXISTS `sp_deletarCurso`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarCurso`(idCurso integer(11))
BEGIN
DELETE FROM `Curso`
WHERE `Curso`.`idCurso` = idCurso;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarCurso
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_listarCurso`;

DELIMITER $$


CREATE PROCEDURE `sp_listarCurso`()
BEGIN
SELECT * FROM`Curso`;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirAgendamento
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirAgendamento`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirAgendamento`(motivo varchar(100), dataHora DATETIME, idProfessorFK integer(11), idAlunoFK integer(11))
BEGIN
  INSERT INTO `Agendamento`
(`motivo`,
`dataHora`,
`idProfessorFK`,
`idAlunoFK`
)
VALUES
(motivo, dataHora, idProfessorFK, idAlunoFK);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarAgendamento
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarAgendamento`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarAgendamento` (idAgendamento integer(11), motivo varchar(100), dataHora DATETIME, idProfessorFK integer(11), idAlunoFK integer(11))
BEGIN
  UPDATE `Agendamento`
    SET 
`motivo`= motivo, 
`dataHora`= dataHora,
`idProfessorFK`= idProfessorFK,
`idAlunoFK`= idAlunoFK

WHERE `Agendamento`.`idAgendamento`=idAgendamento;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarAgendamento
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_deletarAgendamento`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarAgendamento`(idAgendamento integer(11))
BEGIN
DELETE FROM `Agendamento`
WHERE `Agendamento`.`idAgendamento` = idAgendamento;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarAgendamento
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_listarAgendamento`;

DELIMITER $$


CREATE PROCEDURE `sp_listarAgendamento`()
BEGIN
SELECT * FROM`Agendamento`;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirLinhaPesquisa
-- ------------------------------------------------------


DROP procedure IF EXISTS `sp_inserirLinhaPesquisa`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirLinhaPesquisa`(nome varchar(250), idCursoFK integer(11))
BEGIN
  INSERT INTO `LinhaPesquisa`
(`nome`,
`idCursoFK`
)
VALUES
(nome, ìdCursoFK);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarLinhaPesquisa
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarLinhaPesquisa`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarLinhaPesquisa` (idLinhaPesquisa integer(11), nome varchar(250), idCursoFK integer(11))
BEGIN
  UPDATE `LinhaPesquisa`
    SET 
`nome`= nome,
`idCursoFK`= idCursoFK

WHERE `LinhaPesquisa`.`idLinhaPesquisa`= idLinhaPesquisa;
END$$

DELIMITER ; 


-- ------------------------------------------------------
-- procedure sp_deletarLinhaPesquisa
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_deletarLinhaPesquisa`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarLinhaPesquisa`(idLinhaPesquisa integer(11))
BEGIN
DELETE FROM `LinhaPesquisa`
WHERE `LinhaPesquisa`.`idLinhaPesquisa` = idLinhaPesquisa;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarLinhaPesquisa
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_listarLinhaPesquisa`;

DELIMITER $$


CREATE PROCEDURE `sp_listarLinhaPesquisa`()
BEGIN
SELECT * FROM`LinhaPesquisa` ORDER BY nome ASC;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirTCC
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirTCC`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirTCC`(titulo varchar(100), resumo varchar(250), statusTCC tinyint(1), objetivo varchar(100), justificativa varchar(100), TCCTipo tinyint(1), idLinhaPesquisaFK integer(11))
BEGIN
  INSERT INTO `TCC`
(`titulo`,
`resumo`,
`statusTCC`,
`objetivo`,
`justificativa`,
`TCCTipo`,
`idLinhaPesquisaFK`
)
VALUES
(titulo, resumo, statusTCC, objetivo, justificativa, TCCTipo, idLinhaPesquisaFK);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarTCC
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarTCC`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarTCC` (idTCC integer(11), titulo varchar(100), resumo varchar(250), statusTCC tinyint(1), objetivo varchar(100), justificativa varchar(100), TCCTipo tinyint(1), idLinhaPesquisaFK integer(11)) 
BEGIN
  UPDATE `TCC`
    SET 
`titulo` = titulo,
`resumo`= resumo,
`statusTCC`= statusTCC,
`objetivo`= objetivo,
`justificativa`= justificativa, 
`TCCTipo`= TCCTipo,
`idLinhaPesquisaFK`= idLinhaPesquisaFK
WHERE `TCC`.`idTCC`=idTCC;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarTCC
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_deletarTCC`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarTCC`(idTCC integer(11))
BEGIN
DELETE FROM `TCC`
WHERE `TCC`.`idTCC` = idTCC;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarTCC
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_listarTCC`;

DELIMITER $$


CREATE PROCEDURE `sp_listarTCC`()
BEGIN
SELECT * FROM `TCC` ORDER BY  titulo ASC;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirArquivo
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirArquivo`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirArquivo`(link varchar(250), idTCCFK integer(11), versao varchar(45))
BEGIN
  INSERT INTO `Arquivo`
(`link`,
`idTCCFK`,
`versao`
)
VALUES
(link, idTCCFK, versao);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarArquivo
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarArquivo`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarArquivo` (idArquivo integer(11), link varchar(250), idTCCFK integer(11), versao varchar(45))
BEGIN
  UPDATE `Arquivo`
    SET 
`link`= link,
`idTCCFK`= idTCCFK,
`versao`= versao
WHERE `Arquivo`.`idArquivo`=idArquivo;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarArquivo
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_deletarArquivo`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarArquivo`(idArquivo integer(11))
BEGIN
DELETE FROM `Arquivo`
WHERE `Arquivo`.`idArquivo` = idArquivo;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarArquivo
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_listarArquivo`;

DELIMITER $$


CREATE PROCEDURE `sp_listarArquivo`()
BEGIN
SELECT `link`,DISTINCT (`idTCCFK`) ,`versao` FROM `Arquivo` ORDER BY DESC;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirAtividade
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirAtividade`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirAtividade` (nome varchar(50), mes date, descricao varchar(250), idTCCFK integer(11))
BEGIN
  INSERT INTO `Atividade`
(`nome`,
`mes`,
`descricao`,
`idTCCFK`
)
VALUES
(nome, mes, descricao, idTCCFK);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarAtividade
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarAtividade`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarAtividade` (idAtividade integer(11), nome varchar(50), mes date, descricao varchar(250), idTCCFK integer(11))
BEGIN
  UPDATE `Atividade`
    SET 
`nome`= nome,
`mes`= mes,
`descricao`= descricao,
`idTCCFK`= idTCCFK 
WHERE `Atividade`.`idAtividade`=idAtividade;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarAtividade
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_deletarAtividade`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarAtividade`(idAtividade integer(11))
BEGIN
DELETE FROM `Atividade`
WHERE `Atividade`.`idAtividade` = idAtividade;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarAtividade
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_listarAtividade`;

DELIMITER $$


CREATE PROCEDURE `sp_listarAtividade`()
BEGIN
SELECT * FROM `Atividade` ORDER BY MES DESC;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirCronograma
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirCronograma`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirCronograma`(oque varchar(100), porque varchar(100), onde varchar(100), quando varchar(100), quem varchar(100), como varchar(100), quanto varchar(45))
BEGIN
  INSERT INTO `Cronograma`
(`oque`,
`porque`,
`onde`,
`quando`,
`quem`,
`como`,
`quanto`
)
VALUES
(oque, porque, onde, quando, quem, como, quanto);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarCronograma
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarCronograma`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarCronograma` (idCronograma integer(11), oque varchar(100), porque varchar(100), onde varchar(100), quando varchar(100), quem varchar(100), como varchar(100), quanto varchar(45))
BEGIN
  UPDATE `Cronograma`
    SET 
`oque`= oque,
`porque`= porque,
`onde`= onde,
`quando`= quando,
`quem`= quem,
`como`= como,
`quanto`= quanto
WHERE `Cronograma`.`idCronograma`=idCronograma;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarCronograma
-- ------------------------------------------------------
--
--DROP procedure IF EXISTS `sp_deletarCronograma`;
--
--DELIMITER $$
--
--CREATE PROCEDURE `sp_deletarCronograma`(idCronograma integer(11))
--BEGIN
--DELETE FROM `Cronograma`
--WHERE `Cronograma`.`idCronograma` = idCronograma;
--END$$
--
--ELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarCronograma
-- ------------------------------------------------------
--
--DROP procedure IF EXISTS `sp_listarCronograma`;

--DELIMITER $$
--

--CREATE PROCEDURE `sp_listarCronograma`()
--BEGIN
--SELECT * FROM `Cronograma`;
--END$$

--DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirAtividadesCronograma
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirAtividadesCronograma`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirAtividadesCronograma`(nome varchar(100), idCronogramaFK integer(11), idTCCFK integer(11))
BEGIN
  INSERT INTO `AtividadesCronograma`
(`nome`,
`idCronogramaFK`,
`idTCCFK`
)
VALUES
(nome, idCronogramaFK, idTCCFK);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarAtividadesCronograma
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarAtividadesCronograma`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarAtividadesCronograma` (idAtividadesCronograma integer(11), nome varchar(100), idCronogramaFK integer(11), idTCCFK integer(11))
BEGIN
  UPDATE `AtividadesCronograma`
    SET 
`nome`= nome,
`idCronogramaFK`= idCronogramaFK,
`idTCCFK`= idTCCFK
WHERE `AtividadesCronograma`.`idAtividadesCronograma`=idAtividadesCronograma;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarAtividadesCronograma
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_deletarAtividadesCronograma`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarAtividadesCronograma`(idAtividadesCronograma integer(11))
BEGIN
DELETE FROM `Professor`
WHERE `AtividadesCronograma`.`idAtividadesCronograma` = idAtividadesCronograma;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarAtividadesCronograma
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_listarAtividadesCronograma`;

DELIMITER $$


CREATE PROCEDURE `sp_listarAtividadesCronograma`()
BEGIN
SELECT * FROM `AtividadesCronograma`;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirComponentes
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirComponentes`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirComponentes`(idProfessorFK integer(11), idAlunoFK1 integer(11), idAlunoFK2 integer(11), idTCCFK integer(11))
BEGIN
  INSERT INTO `Componentes`
(`idProfessorFK`,
`idAlunoFK1`,
`idAlunoFK2`,
`idTCCFK`
)
VALUES
(idProfessorFK, idAlunoFK1, idAlunoFK2, idTCCFK);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarComponentes
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarComponentes`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarComponentes` (idTCCFK integer(11), idProfessorFK integer(11), idAlunoFK1 integer(11), idAlunoFK2 integer(11))
BEGIN
  UPDATE `Componentes`
    SET 
`idProfessorFK` = idProfessorFK,
`idAlunoFK1`= idAlunoFK1,
`idAlunoFK2`= idAlunoFK2,
`idTCCFK` = idTCCFK
WHERE `Componentes`.`idTCCFK`=idTCCFK;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarComponentes 
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_deletarComponentes`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarComponentes`(idTCCFK integer(11))
BEGIN
DELETE FROM `Componentes`
WHERE `Componentes`.`idTCCFK` = idTCCFK ;
END$$

DELIMITER ;

-- obs: TENTAR FAZER EFEITO CASCATA COM A TABELA TCC

-- ------------------------------------------------------
-- procedure sp_listarComponentes
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_listarComponentes`;

DELIMITER $$


CREATE PROCEDURE `sp_listarComponentes`()
BEGIN
SELECT * FROM `Componentes`
END$$

DELIMITER ;

-- obs: FAZER INNER JOIN COM PROFESSOR E ALUNO --------------
-- obs: FAZER INNER JOIN COM TCC  ---------------------------

-- ------------------------------------------------------
-- procedure sp_inserirUnidade
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirUnidade`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirUnidade`(nome varchar(45))
BEGIN
  INSERT INTO `Unidade`
(`nome`,
)
VALUES
(nome);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarUnidade
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarUnidade`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarUnidade` (idUnidade integer(11), nome varchar(45))
BEGIN
  UPDATE `Unidade`
    SET 
`nome`= nome
WHERE `Unidade`.`idUnidade`=idUnidade;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarUnidade
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_deletarUnidade`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarUnidade`(idUnidade integer(11))
BEGIN
DELETE FROM `Unidade`
WHERE `Unidade`.`idUnidade` = idUnidade;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarUnidade
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_listarUnidade`;

DELIMITER $$


CREATE PROCEDURE `sp_listarUnidade`()
BEGIN
SELECT * FROM `Unidade` ORDER BY nome ASC;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirSala
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirSala`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirSala`(setor varchar(10), nome varchar (20), capacidade integer, idUnidadeFK integer)
BEGIN
  INSERT INTO `Sala`
(`setor`,
`nome`,
`capacidade`,
`idUnidadeFK`
)
VALUES
(setor, nome,capacidade, idUnidadeFK);
END$$

DELIMITER ;


-- ------------------------------------------------------
-- procedure sp_alterarSala
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarSala`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarSala` (idSala integer(11), setor varchar(10), nome varchar (20), capacidade integer, idUnidadeFK integer)
BEGIN
  UPDATE `Sala`
    SET 
`setor`= setor,
`nome` = nome,
`capacidade`= capacidade,
`idUnidadeFK`= idUnidadeFK
WHERE `Sala`.`idSala`=idSala;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarSala
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_deletarSala`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarSala`(idSala integer(11))
BEGIN
DELETE FROM `Sala`
WHERE `Sala`.`idSala` = idSala;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarSala
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_listarSala`;

DELIMITER $$


CREATE PROCEDURE `sp_listarSala`()
BEGIN
SELECT * FROM `Sala` AS S INNER JOIN `Unidade` AS U ON S.`idUnidadeFK` = U.`idUnidade` ORDER BY U.`nome` ASC, S.`nome` ASC;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirReserva
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirReserva`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirReserva`(dataHora DATETIME, idProfessorFK integer(11), idSalaFK integer(11))
BEGIN
  INSERT INTO `Reserva`
(`dataHora`,
`idProfessorFK`,
`idSalaFK`
)
VALUES
(dataHora, idProfessorFK, idSalaFK);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarReserva
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarReserva`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarReserva` (idReserva integer(11), dataHora DATETIME, idProfessorFK integer(11), idSalaFK integer(11))
BEGIN
  UPDATE `Reserva`
    SET 
`dataHora`= dataHora,
`idProfessorFK`= idProfessorFK,
`idSalaFK`= idSalaFK
WHERE `Reserva`.`idReserva`=idReserva;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarReserva
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_deletarReserva`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarReserva`(idReserva integer(11))
BEGIN
DELETE FROM `Reserva`
WHERE `Reserva`.`idReserva` = idReserva;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarReserva
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_listarReserva`;
ELIMITER $$JH


CREATE PROCEDURE `sp_listarReserva`()
BEGIN
SELECT * FROM `Reserva` ORDER BY dataHora DESC;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirDefesa
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirDefesa`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirDefesa`(data DATETIME, idTCCFK integer(11), idReservaFK INT(11))
BEGIN
  INSERT INTO `Defesa`
(`data`,
`idTCCFK`,
`idReservaFK`
)
VALUES
(data, idTCCFK, idReservaFK);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarDefesa
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarDefesa`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarDefesa` (idDefesa integer(11), data DATETIME, idTCCFK integer(11), idReservaFK INT(11))
BEGIN
  UPDATE `Defesa`
    SET 
`data`= data,
`idTCCFK`= idTCCFK,
`idReservaFK`= idReservaFK
WHERE `Defesa`.`idDefesa`=idDefesa;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarDefesa
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_deletarDefesa`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarDefesa`(idDefesa integer(11))
BEGIN
DELETE FROM `Defesa`
WHERE `Defesa`.`idDefesa` = idDefesa;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarDefesa
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_listarDefesa`;

DELIMITER $$


CREATE PROCEDURE `sp_listarDefesa`()
BEGIN
SELECT * FROM `Defesa`;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirErros
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirErros`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirErros`(nomeErro varchar(50), categoria varchar(100))
BEGIN
  INSERT INTO `Erros`
(`nomeErro`,
`categoria`
)
VALUES
(nomeErro, categoria);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarErros
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarErros`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarErros` (idErros integer(11),nomeErro varchar(50), categoria varchar(100))
BEGIN
  UPDATE `Erros`
    SET 
`nomeErro`= nomeErro,
`categoria`= categoria
WHERE `Erros`.`idErros`=idErros;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarErros
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_deletarErros`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarErros`(idErros integer(11))
BEGIN
DELETE FROM `Erros`
WHERE `Erros`.`idErros` = idErros;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarErros
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_listarErros`;

DELIMITER $$


CREATE PROCEDURE `sp_listarErros`()
BEGIN
SELECT * FROM `Erros` ORDER BY nomeErro ASC;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirErrosTCC
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirErrosTCC`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirErrosTCC`(idTCCFK integer(11), idErrosFK integer(11))
BEGIN
  INSERT INTO `ErrosTCC`
(`idTCCFK`,
`idErrosFK`
)
VALUES
(idTCCFK, idErrosFK);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarErrosTCC
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarErrosTCC`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarErrosTCC` (idErrosTCC integer(11), idTCCFK integer(11), idErrosFK integer(11))
BEGIN
  UPDATE `ErrosTCC`
    SET 
`idTCCFK`= idTCCFK,
`idErrosFK`= idErrosFK
WHERE `ErrosTCC`.`idErrosTCC`=idErrosTCC;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarErrosTCC
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_deletarErrosTCC`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarErrosTCC`(idErrosTCC integer(11))
BEGIN
DELETE FROM `ErrosTCC`
WHERE `ErrosTCC`.`idErrosTCC` = idErrosTCC;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarErrosTCC
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_listarErrosTCC`;

DELIMITER $$


CREATE PROCEDURE `sp_listarErrosTCC`()
BEGIN
SELECT * FROM `ErrosTCC`;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirEvento
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirEvento`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirEvento`(nome varchar(50), dataHora datetime, local varchar(100), idProfessorFK integer(11), idCursoFK integer(11))
BEGIN
  INSERT INTO `Evento`
(`nome`,
`dataHora`,
`local`,
`idProfessorFK`,
`idCursoFK`
)
VALUES
(nome, dataHora, local, idProfessorFK, idCursoFK);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarEvento
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarEvento`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarEvento` (idEvento integer(11), nome varchar(50), dataHora datetime, local varchar(100), idProfessorFK integer(11), idCursoFK integer(11))
BEGIN
  UPDATE `Evento`
    SET 
`nome`= nome,
`dataHora`= dataHora,
`local`= local,
`idProfessorFK`= idProfessorFK,
`idCursoFK`= idCursoFK 
WHERE `Evento`.`idEvento`=idEvento;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarEvento
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_deletarEvento`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarEvento`(idEvento integer(11))
BEGIN
DELETE FROM `Evento`
WHERE `Evento`.`idEvento` = idEvento;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarEvento
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_listarEvento`;

DELIMITER $$


CREATE PROCEDURE `sp_listarEvento`()
BEGIN
SELECT * FROM `Evento`;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirRelatorio
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirRelatorio`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirRelatorio`(apresentacaoNota FLOAT, data DATETIME, fundamentacaoNota FLOAT, desenvolvimentoNota FLOAT, resultadosNota FLOAT, notaFinal FLOAT, 
  TipoRelatorio varchar(50), apresentacaoComentario varchar(250), fundamentacaoComentario varchar(250), desenvolvimentoComentario varchar(250), 
  resultadosComentario varchar(250), idTCCFK integer(11))
BEGIN
  INSERT INTO `Relatorio`
(`apresentacaoNota`,
`data`,
`fundamentacaoNota`,
`desenvolvimentoNota`,
`resultadosNota`,
`notaFinal`,
`TipoRelatorio`, 
`apresentacaoComentario`,
`fundamentacaoComentario`,
`desenvolvimentoComentario`,
`resultadosComentario`,
`idTCCFK`
)
VALUES
(apresentacaoNota, data, fundamentacaoNota, desenvolvimentoNota, resultadosNota, notaFinal, TipoRelatorio, apresentacaoComentario, fundamentacaoComentario, desenvolvimentoComentario, resultadosComentario, idTCCFK);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarRelatorio
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarRelatorio`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarRelatorio` (idRelatorio integer(11), data DATETIME, apresentacaoNota FLOAT, fundamentacaoNota FLOAT, desenvolvimentoNota FLOAT, resultadosNota FLOAT, notaFinal FLOAT, 
  TipoRelatorio varchar(50), apresentacaoComentario varchar(250), fundamentacaoComentario varchar(250), desenvolvimentoComentario varchar(250), 
  resultadosComentario varchar(250), idTCCFK integer(11))
BEGIN
  UPDATE `Relatorio`
    SET 
`apresentacaoNota`= apresentacaoNota,
`data`= data,
`fundamentacaoNota`= fundamentacaoNota,
`desenvolvimentoNota`= desenvolvimentoNota,
`resultadosNota`= resultadosNota,
`notaFinal`= notaFinal,
`TipoRelatorio`= TipoRelatorio, 
`apresentacaoComentario`= apresentacaoComentario,
`fundamentacaoComentario`= fundamentacaoComentario,
`desenvolvimentoComentario`= desenvolvimentoComentario,
`resultadosComentario`= resultadosComentario,
`idTCCFK`= idTCCFK
WHERE `Relatorio`.`idRelatorio`=idRelatorio;
END$$

DELIMITER ; 

-- ------------------------------------------------------
-- procedure sp_deletarRelatorio
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_deletarRelatorio`;

DELIMITER $$

CREATE PROCEDURE `sp_deletarRelatorio`(idRelatorio integer(11))
BEGIN
DELETE FROM `Relatorio`
WHERE `Relatorio`.`idRelatorio` = idRelatorio;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarRelatorio
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_listarRelatorio`;

DELIMITER $$


CREATE PROCEDURE `sp_listarRelatorio`()
BEGIN
SELECT T.`titulo`, R.`data`, R.`apresentacaoNota`, R.`fundamentacaoNota`, R.`desenvolvimentoNota`, R.`resultadosNota`, R.`notaFinal`, 
R.`TipoRelatorio`, R.`apresentacaoComentario`, R.`fundamentacaoComentario`, R.`desenvolvimentoComentario`, R.`resultadosComentario`
 FROM `Relatorio` AS R INNER JOIN `TCC` AS T ON R.`idTCCFK` = T.`idTCC` ORDER BY R.`data` ASC, T.`titulo` ASC;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_inserirAlunoDefesa
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_inserirAlunoDefesa`;

DELIMITER $$

CREATE PROCEDURE `sp_inserirAlunoDefesa`(notaPostura FLOAT, notaComunicacao FLOAT, notaClareza FLOAT, notaDominio FLOAT, idAluno integer(11), notaFinal FLOAT, 
 posturaComentario varchar(200), comunicacaoComentario varchar(45), clarezaComentario varchar(45), dominioComentario varchar(45), idDefesa integer(11))
BEGIN
  INSERT INTO `AlunoDefesa`
(`notaPostura`,
`notaComunicacao`,
`notaClareza`,
`notaDominio`,
`idAluno`,
`notaFinal`,
`posturaComentario`,
`comunicacaoComentario`,
`clarezaComentario`,
`dominioComentario`,
`idDefesa`
)
VALUES
(notaPostura, notaComunicacao, notaClareza, notaDominio, idAluno, notaFinal, posturaComentario, comunicacaoComentario, clarezaComentario, dominioComentario, idDefesa);
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_alterarAlunoDefesa
-- ------------------------------------------------------

DROP procedure IF EXISTS `sp_alterarAlunoDefesa`;

DELIMITER $$

CREATE PROCEDURE `sp_alterarAlunoDefesa` (notaPostura FLOAT, notaComunicacao FLOAT, notaClareza FLOAT, notaDominio FLOAT, idAluno integer(11), notaFinal FLOAT, 
 posturaComentario varchar(200), comunicacaoComentario varchar(45), clarezaComentario varchar(45), dominioComentario varchar(45), idDefesa integer(11))

BEGIN
  UPDATE `AlunoDefesa`
    SET 
`notaPostura`= notaPostura,
`notaComunicacao`= notaComunicacao,
`notaClareza`= notaClareza,
`notaDominio`= notaDominio,
`idAluno`= idAluno,
`notaFinal`= notaFinal,
`posturaComentario`= posturaComentario,
`comunicacaoComentario`= comunicacaoComentario,
`clarezaComentario`= clarezaComentario,
`dominioComentario`= dominioComentario,
`idDefesa`= idDefesa
WHERE `AlunoDefesa`.`idTCC`=idTCC;
END$$

DELIMITER ; 


-- ------------------------------------------------------
-- procedure sp_listarAlunoDefesa_idAluno
-- ------------------------------------------------------


DROP procedure IF EXISTS `sp_listarAlunoDefesa_idAluno`;

DELIMITER $$


CREATE PROCEDURE `sp_listarAlunoDefesa_idAluno`()
BEGIN
SELECT * FROM `AlunoDefesa`order by idAluno ASC;
END$$

DELIMITER ;

-- ------------------------------------------------------
-- procedure sp_listarAlunoDefesa_Geral
-- ------------------------------------------------------


DROP procedure IF EXISTS `sp_listarAlunoDefesa_Geral`;

DELIMITER $$


CREATE PROCEDURE `sp_listarAlunoDefesa_Geral`()
BEGIN
SELECT A.`nome`, AD.`notaPostura`, AD.`notaComunicacao`, AD.`notaClareza`, AD.`notaDominio`, AD.`notaFinal`, AD.`posturaComentario`, 
AD.`comunicacaoComentario`, AD.`clarezaComentario`, AD.`dominioComentario`, AD.`idDefesa`
 FROM `AlunoDefesa` AS AD INNER JOIN `Aluno` AS A ON AD.`idAluno`= A.`idAluno` order by A.`nome` ASC;
END$$

DELIMITER ;

-----------------------------------

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Teste de Procedures

-- call sp_inserirAluno('Aluno teste', '123456789', 'aluno@teste.com', 'aluno.Teste', '123456', 3);
-- call sp_listarAluno();
-- call sp_buscarAlunoID(1);
-- call sp_deletarAluno(1);
